name: 'Cypress Screenshot & Video Upload to Slack'
branding:
  icon: file
  color: blue
description: 'After running a Cypress test in a Github action, upload the screenshots and videos directly to Slack'
inputs:
  action:
    description: 'Action to take: start, upload, finish'
    required: true
  token:
    description: 'Slack token'
    required: true
  channel:
    description: 'Slack channel name'
    required: true
  screenshots:
    description: 'The path of the directory where Cypress stores its screenshots. Defaults to `./cypress/screenshots`. No trailing slashes, please.'
    required: false
  videos:
    description: 'The path of the directory where Cypress stores its videos. Defaults to `./cypress/videos`. No trailing slashes, please.'
    required: false
  message-text:
    description: 'Slack message text'
    required: true
  thread-id:
    description: 'Thread to edit/continue in'
    required: false
  status:
    description: 'Status of run - for finish action'
    required: false
  author:
    description: 'The author'
    required: true
outputs:
  thread-id:
    description: 'Thread ID'
  result:
    description: 'Result of video and screenshot uploads'
runs:
  using: 'node16'
  main: 'dist/index.js'
